# Generated by Django 4.1.6 on 2023-02-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.CharField(max_length=1200, verbose_name='contenido')),
                ('edit', models.BooleanField(default=True, verbose_name='Editable')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.category', verbose_name='Category')),
                ('fk_tags', models.ManyToManyField(blank=True, null=True, to='wiki.tag')),
            ],
        ),
    ]
